select * from customer limit 20

--What is the total revenue generated by male vs. female customers I
select gender,SUM(purchase_amount)as revenue
from customer
group by gender

-- Which are the top 5 products with the highest average review rating?
select item_purchased,ROUND (AVG (review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased 
order by avg(review_rating) desc
limit 5;

-- Compare the average Purchase Amounts between Standard and Express Shipping-
select shipping_type,
AVG(purchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-su
select subscription_status,
count(customer_id) as total_cutomers,
round (avg(purchase_amount),2) as avg_spend,
round (sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue , avg_spend desc ;

--are cutomers who are repeat buyers more than 5 purchases also likely to subscribe?
select subscription_status ,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--what is the revenue contribution of each age group 
select age_group,
sum(purchase_amount) as total_revenue 
from customer
group by age_group
order by total_revenue desc;
